dependencies:
#  - julia
  - matplotlib
  - numpy
  - scipy
  - sympy
  - ipywidgets >=7.5.1
  - jupyterlab >=1.2.6
  - notebook >=6.*.*
  - pip
  - pytest
  - pip:
      - julia
      - nbval
      - nbdime
      - jupyterlab_latex
      - ipypublish
