dependencies:
#  - julia
  - matplotlib
  - numpy
  - scipy
  - sympy
  - ipywidgets
  - jupyterlab =0.35
  - notebook =5.7.4
  - pip
  - pytest
  - pip:
      - julia
      - nbval
      - nbdime
      - jupyterlab_latex
      - ipypublish
